### PR TITLE
Hotfix: Replace HTTP with HTTPS

### PR DESCRIPTION
**Pull request by jacobvenable**
This quick fix simply replaces an links found in the CSS or HTML components, and updates them from HTTP to HTTPS.

The `gulp-rename` node package was also added as a dev dependency to the package.json.

### CODE REVIEW

**Comment by jengarza** [comment]
Looks good to me.

**Review by bholaday — COMMENTED** [review]
a-ok by me

**Comment by bholaday** [comment]
Did you want to reference style.min.css?

**Comment by jacobvenable** [comment]
@bholaday Usually I'll replace the style.css that lives on the server with the minified version.

**Pull request merged**
